version: "3.8"
services:
  bot:
    build: .
    entrypoint: jurigged -v bot.py
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    configs:
      - source: code-review-config
        target: /app/config.yaml
    secrets:
      - source: code-review-secrets
        target: /app/secrets.yaml
      - source: ssh-key
        target: /root/.ssh/id_ed25519
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: codereview
      MYSQL_USER: codereviewuser
      MYSQL_PASSWORD: testpassword
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    expose:
      - "3306"
    volumes:
      - code-review-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 1s
      interval: 1s
      retries: 10
configs:
  code-review-config:
    file: ./config.yaml
secrets:
  code-review-secrets:
    file: ./secrets.yaml
  ssh-key:
    file: ~/.ssh/id_ed25519
volumes:
  code-review-db:
