version: "3.8"
services:
  prod-bot:
    build: .
    depends_on:
      prod-db:
        condition: service_healthy
    links:
      - prod-db
    configs:
      - source: code-review-config-prod
        target: /app/config.yaml
    secrets:
      - source: code-review-secrets-prod
        target: /app/secrets.yaml
  prod-db:
    image: mysql
    environment:
      MYSQL_DATABASE: codereview
      MYSQL_USER: codereviewuser
      MYSQL_PASSWORD: ${PROD_DB_PASSWORD}
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    expose:
      - '3306'
    volumes:
      - code-review-db-prod:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 1s
      interval: 1s
      retries: 10
configs:
  code-review-config-prod:
    file: ./config-prod.yaml
secrets:
  code-review-secrets-prod:
    file: ./secrets-prod.yaml
volumes:
  code-review-db-prod: